version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: skillswap_db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: ***REMOVED-DB-PASSWORD***
      POSTGRES_DB: skillswap
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  # Додаємо Adminer для зручного перегляду бази в браузері
  adminer:
    image: adminer:latest
    container_name: skillswap_adminer
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    restart: unless-stopped

  # ДОДАНО: Контейнер з Redis для кешування
  redis:
    image: redis:alpine
    container_name: skillswap_redis
    ports:
      - "6379:6379"
    restart: unless-stopped

volumes:
  pgdata: